# Shopify App Configuration

name = "PrintAIze"
client_id = "97a6a26f3c4ace1c2b7bd2df406f1f29"
application_url = "https://printaize.vercel.app"
embedded = true

[access_scopes]
scopes = "write_products,read_customers"

[auth]
redirect_urls = [
  "https://printaize.vercel.app/auth/callback",
  "https://printaize.com/auth/callback",
  "https://printaize.myshopify.com/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "printaize.myshopify.com"
