# Shopify App Configuration

name = "PrintAIze"
client_id = ""
application_url = "https://printaize.vercel.app"
embedded = true

[access_scopes]
scopes = "write_products,read_customers"

[auth]
redirect_urls = [
  "https://printaize.vercel.app/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
